version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "schedule"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
  express:
    build: ./yet-another-schedule-app-backend
    networks:
      - default
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://username:password@postgres:5432/schedule?schema=public
      - SECRET_TOKEN=SECRET_TOKEN
      - PARSER_URL=http://parser-api:5000/api
  nginx:
    build: ./yet-another-schedule-app-frontend
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - express

networks:
  default:
    external: false

volumes:
  postgres-data: